/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as DocsThemingRouteImport } from './routes/docs.theming'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/themes': typeof ThemesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/changelog': typeof ChangelogRoute
  '/themes': typeof ThemesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/themes': typeof ThemesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/theming': typeof DocsThemingRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/changelog'
    | '/docs'
    | '/themes'
    | '/components/$slug'
    | '/docs/cli'
    | '/docs/installation'
    | '/docs/theming'
    | '/components/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/changelog'
    | '/themes'
    | '/components/$slug'
    | '/docs/cli'
    | '/docs/installation'
    | '/docs/theming'
    | '/components'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/changelog'
    | '/docs'
    | '/themes'
    | '/components/$slug'
    | '/docs/cli'
    | '/docs/installation'
    | '/docs/theming'
    | '/components/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  ThemesRoute: typeof ThemesRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsCliRoute: typeof DocsCliRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCliRoute: DocsCliRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  ThemesRoute: ThemesRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
